### ISSUE TITLE
Bug?: Squirrel reads only first closure in .sq files

### ISSUE THREAD

**Issue by KelvinShadewing** [albertodemichelis/squirrel#101]
I wrote a small program that compiles multiple `.nut` files into a single `.sq`, but when I run the compiled script, it only executes the first closure in the file. I can't tell if maybe it's adding an `EOF` character and this is just something on my end (when I open it in a text editor, it shows the full file, which I can tell by string values showing up from multiple files), or if maybe it's supposed to only read one. If it's only programmed to read the first closure, could that be changed so that multi-source scripts can be packed together? I don't want to merge me sources before building because then I won't get correct line numbers from error reporting. If it is supposed to read multiple, and I'm not somehow accidentally adding `EOF` when my compiler merges them, then I guess this would count as a bug.

If anyone would like to double check my project, it's [here](https://github.com/KelvinShadewing/Squake).

**Comment by zeromus** [comment]
You would use readclosure() to get the contents of the file into squirrel for executing. That's singular. There is no readclosures() which reads several closures. There's no format for storing several closures and there's no function for reading no format. You'll need to make your own format.

**Comment by KelvinShadewing** [comment]
OK, is there a special character or something that delimits closures for me to load them into a vector or something?

**Comment by zeromus** [comment]
If it were me, I would write an index with exactly what I needed: "your own format".

the closure knows when to stop reading. you should just be able to concatenate them, if you know how many to read. you can know when you're done reading them because the stream's position will match it's length (you could also read one character and then unread it unless it's EOF).

You want to inspect SQClosure::Load in sqobject.cpp; there's a special marker for the end of the closure.
