### ISSUE TITLE
issue with srand

### ISSUE THREAD

**Issue by keilmillerjr** [albertodemichelis/squirrel#172]
I am using an app ([attractmode](https://github.com/mickelson/attract) mac os x) with squirrel lang 3.0.4. Having an issue with srand.

- time() is generating unique times, verified printing to console.
- srand(time()) is generating the same seed every time.

srand(0) generates a seed, but srand with anything else as a parameter creates a different but non unique seed. I can only obtain two different seeds. Any ideas? Here’s a link to my project [rantro-intro](https://github.com/keilmillerjr/randtro-intro/).

**Comment by zeromus** [comment]
works fine for me, using some 1 year old build of squirrel, and I don't see any reason why it wouldn't work. The problem is probably best addressed to whoever integrated squirrel in attractmode. It's possible it takes ownership of srand (using it for its own internal purposes) and either intends for you to use another rand which it provided, or forgot to provide you a new one. in general using functions like this tightly coupled to the CRT is a poor idea. IMO you shouldn't be using these in an embedded squirrel.

**Comment by keilmillerjr** [comment]
Apparently seems need to be vastly different to provide proper results. Time in seconds is not enough. I looked at some python libraries for reference. Thank you.

**Comment by keilmillerjr** [comment]
@zeromus "quick succession it will have no useful randomizing" was the exact issue I have seen. The function I have now seems to be working great on my mac. I’m not too worried since about it breaking since its a simple method of bit shifting that I have used on PLC’s. What would be good values was unknown to me, so some one else seemed to know more than I. I will have a friend look help through the app source and maybe I can integrate and provide a pull request. Thank you!
