### ISSUE TITLE
backup/restore state, or serialize data

### ISSUE THREAD

**Issue by tYYGH** [albertodemichelis/squirrel#173]
I am using squirrel-lang in the game BlackVoxel. I tried to test data serialization for the “programmable robot”, which looks like this (my current best guess…):

```squirrel
Key <- 0;

function Voxel_Step() {
  for (local i=0;i<128;i++) {
    if (GetKey(i)) {
      print("Key Pressed : " + i + "\n");
      Key = i;
    }
  }
}

// This function is called when robot is loaded from save file or when created
function Voxel_Load() {
  local save = dofile(GetPath(4) + GetInfo(20) + "test.sav");
  print(save.K);
}

// This function is called when robot is unloaded to save file or when destroyed
function Voxel_Unload() {
   writeclosuretofile(GetPath(4) + GetInfo(20) + "test.sav", getData);
}

function getData() {
  return {
    K = Key
  };
}
```

I’m new to this language, so maybe it’s completely wrong… My goal is to save the state data (here: `Key`), and restore it when I restart the game.
In my test, I press a key, and I see its code printed (105), then I quit the game, and load it back, but the value printed is 0, not 105.

**Comment by zeromus** [comment]
serializing the getData closure doesn't bring the global variable along with it. it's absurd to serialize the closure, you must just be trying that because it's the only thing in the docs that looks like serialization. you should find a json serializing library for squirrel. or you may need to write your own. serialization is complex and canned solutions do not always work. in particular you will have problems the moment one robot stores a reference to another. If you're the developer of BlackVoxel, you can add json serializing to the engine. If you're a user of BlackVoxel, you should be getting support from BlackVoxel, as it may have its own provisions for serializing data.

**Comment by tYYGH** [comment]
Hi @zeromus, and thank you for your answer :-) I’m just a user, and the BlackVoxel library is _very_ limited (http://www.blackvoxel.com/view.php?node=1317): no json, serialization, or the like…
But I’m OK with writing my own stuff, especially since all I have to save is numbers and a table of arrays of numbers, plus one boolean.

Going back to my test above, I noticed, that if I overwrite my `test.sav` file with this plain text:

```
return {
  K = 105
};
```

Then interestingly, the value `105` is **correctly** printed when I load back the game :+1: 
So I wrote the code to generate such a file:

```squirrel
// This function is called when robot is unloaded to save file or when destroyed
function Voxel_Unload() {
  local c;
  local name = GetPath(4) + GetInfo(20) + "test.sav";
  local save = file(name, "w");
  local data;
  local code = "return {\n";
  code += "  K = " + Key + "\n";
  code += "}\n";
  data = blob(code.len());
  foreach ( c in code )
  {
    data.writen(c, 'b');
  }
  save.writeblob(data);
  save.close();
}
```

And it works! That’s good enough for me. Bye
