### ISSUE TITLE
squirrel-lang is down

### ISSUE THREAD

**Issue by TaroEld** [albertodemichelis/squirrel#283]
Hey, it would appear that your squirrel-lang.org domain has expired.

**Comment by RizzoRat** [comment]
my last personal private e-mail contact to alberto was about 10 years ago. Also years ago his personal website went down. Then the wiki and forum about 2 years ago (i think). Now both qnsoftware as well as squirrel-lang apparetly got freed and were bought by godaddy. That is a damn bad sign, happens when freeing the domains delitberately - or not paying for them.
Last news I know is almost a year ago when he joined GOAL, around that time also the twitter account and instagram went silent

Unfortunately, I am afraid either something (bad) happened to him, or or he abandoned Squirrel for whatever reason. Which both is sad

Alberto, if you're alive, at least leave a short note please! Me and probably some others really are worrying. I miss so many people, please don't add to the list

**Comment by TaroEld** [comment]
I just want to mention that he committed to this repo three months ago.

**Comment by VITALISED** [comment]
it's back!

**Comment by albertodemichelis** [comment]
the ISP that has my dns cleared the DNS record for some reason. It took me a while to realize it :P
