### ISSUE TITLE
feature: light explicit "thiscall"

### ISSUE THREAD

**Issue by albertodemichelis** [albertodemichelis/squirrel#52]
In my servers I make heavy use of coroutines, occasionally I need to invoke a function forcing a specific "this". Currently the options are:

```
function doSomething(a,b,c,d) 
{
... something here
}

// existing option 1
// requires to clone the closure(it's good for stuff like UI callbacks etc) 
// more expensive in terms of memory compared to vanilla closure

local _mydosomething = dosomething.bindenv(mythis);
_mydosomething(1,2,3,4);

// existing option 2
// this inject a "C" stack frame, prevents "susepends" and is less efficient than option 1

doSomething.call(mythis,1,2,3,4)
```

I was thinking of adding a new built in syntax that allows to preform a "raw call" what specifies the "this". It doesn't require any change in the VM; just compiler work, so It easy enough.

something like:

```
// idea 1
// add special character($ is ugly but most characters are already taken)
doSomething$(mythis,1,2,3,4)

// idea 2
// or add new keyword "thiscall"
thiscall(doSomething,mythis,1,2,3,4);

```

any better option regarding syntax? any thought?

**Comment by zeromus** [comment]
This is what I was doing just the other day when I was looking at getstackinfos, but I wasn't concerned about performance. 

I can imagine other more exotic things than this, which it would be nice to save special characters for. Maybe enable named/disordered parameters? I don't know how useful that is, but the point is, since there are so few special characters left, you should save them for emergencies. I think the `thiscall` solution is elegant, and the opposite of an emergency. I hate adding keywords too, but there's an infinite number of them and only so many symbols...

On the other hand, you could view this as a special case of named parameters. Suppose you had dosomething(this:mythis, 1,2,3,4).  I don't use named parameters in any other language so I don't know how they mix and match named and not-named, so I don't know how well that would work. But hey, I'm brainstorming.

**Comment by aab29** [comment]
Ooh--interesting idea!  💡 It sounds useful.  ✌️ 

Of the two options that @albertodemichelis provided, I like `thiscall` much better. 🏂  I'd say that in general it's best to avoid using special characters unless those special characters already have a standard meaning in C-based languages.  And if they already have a standard meaning, they should do the same thing in Squirrel that they do in those languages.  🐰  The fewer surprises, the better.  👻  Also, the words `this` and `call` provide enough meaning that a newcomer to the language could probably figure out what the method does without looking it up. 💭  With a plain `$`, there's no way to guess its meaning.  🔮  Of course, these are just my opinions.  👱 ☝️ I think either option would be a welcome improvement.  😎 

As for named parameters, I can't say I've used them in other languages either, but it might be worth looking into them.  👀

**Comment by albertodemichelis** [comment]
ok, I implemented "thiscall" in a record breaking "5 lines of code" :sunglasses: . I'm still thinking if "thiscall" is the best keyword for it.

**Comment by zeromus** [comment]
I thought about trying this out today, but it seems you haven't committed it!

**Comment by albertodemichelis** [comment]
I'm still conflicted about the keyword 'thiscall', 'rawcall' , or something else

**Comment by Eiyeron** [comment]
I actually prefer rawcall, as other calls are wrapping functions which automatically manage `this`.

**Comment by zeromus** [comment]
rawcall might be fine, but think about whether theres anything else rawcall could do which it would be a better name for...

**Comment by albertodemichelis** [comment]
another is 'nakedcall' ! like __declspec(naked) in MSVC++ that omit the function prolog.

**Comment by albertodemichelis** [comment]
I pushed the change, it is called "rawcall"
it works like this

```
function test(a,b)
{
...
}
loca env = { bla = 55 };
local ret = rawcall(test,env,1,"bla");
```
